### PR TITLE
added footer component

### PR DESCRIPTION
**Pull request by NooraJumppanen**
Hi, I added the footer component. But I had trouble understanding where all the icons in the style guide were from, so I only added the home icon. I realized we need to install fontawesome packages to our project and possible packages for other icons as well. Will do another ticket of this to Trello. But please comment if this pull request is ok, thank you!

### CODE REVIEW

**Comment by Termanty** [comment]
Looks good. It's ok for me.

**Comment by Altynay-ayyao** [comment]
It's good.

**Comment by MariaRosenholm** [comment]
Looks good! :)

**Comment by SaaraLeppis** [comment]
Ok for me

**Pull request merged**
