### PR TITLE
New move component

### PR DESCRIPTION
**Pull request by NooraJumppanen**
Added AddMove component and styling to it. Made EditMove and AddMove stylings similiar. Took away the labels from EditMove-page. 

Let's see what conflicts arise when I do the pull request.. :)

### CODE REVIEW

**Comment by NooraJumppanen** [comment]
Let's have a look at this on Thursday morning. :)

**Comment by NooraJumppanen** [comment]
The conflicts are gone now so pls check :)

**Comment by SaaraLeppis** [comment]
Looks good to me!

**Comment by Termanty** [comment]
This feels ok to me!

**Pull request merged**
