### PR TITLE
db.json added for JSON-server

### PR DESCRIPTION
**Pull request by Termanty**
Can you all comment this pull request. When every one gives green light. We can the accept it.

### CODE REVIEW

**Comment by SaaraLeppis** [comment]
Green light

**Comment by MariaRosenholm** [comment]
Ok, this one looks good too! Thank you for the instructions! :)

**Comment by NooraJumppanen** [comment]
This is good, thank you!

**Comment by Altynay-ayyao** [comment]
Thank you, all good !

**Pull request closed without merging**
