### PR TITLE
added header and main to the App.js

### PR DESCRIPTION
**Pull request by MariaRosenholm**
I added the main and header to the App.js.
I will add the footer later when it is ready! 
Please check this and comment so we can merge this one! :)

### CODE REVIEW

**Comment by Termanty** [comment]
Looks good. It's ok for me.

**Comment by NooraJumppanen** [comment]
Good, ok for me!

**Comment by Altynay-ayyao** [comment]
Looks good

**Comment by SaaraLeppis** [comment]
ok for me!

**Pull request merged**
